FROM huggingface/transformers-pytorch-gpu

RUN pip3 install jupyterlab ipywidgets datasets
RUN pip3 install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install git+https://github.com/huggingface/transformers
RUN pip3 install deepspeed

WORKDIR /tmp
RUN git clone https://github.com/NVIDIA/apex
WORKDIR /tmp/apex
RUN pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
RUN apt update && apt install openmpi-bin
